/* ============================================ */
/* DotaScope — Hero Database                     */
/* 124 heroes with win rates & attributes        */
/* CDN: https://cdn.cloudflare.steamstatic.com   */
/* ============================================ */

const HERO_CDN = 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/';

// Hero data: id (OpenDota), name, localized_name, attr (str/agi/int/uni), winRate (approximate 7.38e avg)
const HEROES = [
    { id: 1, n: 'antimage', l: 'Anti-Mage', a: 'agi', w: 49.5 },
    { id: 2, n: 'axe', l: 'Axe', a: 'str', w: 51.2 },
    { id: 3, n: 'bane', l: 'Bane', a: 'uni', w: 51.8 },
    { id: 4, n: 'bloodseeker', l: 'Bloodseeker', a: 'agi', w: 52.3 },
    { id: 5, n: 'crystal_maiden', l: 'Crystal Maiden', a: 'int', w: 50.1 },
    { id: 6, n: 'drow_ranger', l: 'Drow Ranger', a: 'agi', w: 50.8 },
    { id: 7, n: 'earthshaker', l: 'Earthshaker', a: 'str', w: 49.2 },
    { id: 8, n: 'juggernaut', l: 'Juggernaut', a: 'agi', w: 50.5 },
    { id: 9, n: 'mirana', l: 'Mirana', a: 'uni', w: 48.7 },
    { id: 10, n: 'morphling', l: 'Morphling', a: 'agi', w: 47.8 },
    { id: 11, n: 'nevermore', l: 'Shadow Fiend', a: 'agi', w: 49.0 },
    { id: 12, n: 'phantom_lancer', l: 'Phantom Lancer', a: 'agi', w: 50.6 },
    { id: 13, n: 'puck', l: 'Puck', a: 'int', w: 48.5 },
    { id: 14, n: 'pudge', l: 'Pudge', a: 'str', w: 50.2 },
    { id: 15, n: 'razor', l: 'Razor', a: 'agi', w: 49.8 },
    { id: 16, n: 'sand_king', l: 'Sand King', a: 'str', w: 50.5 },
    { id: 17, n: 'storm_spirit', l: 'Storm Spirit', a: 'int', w: 48.3 },
    { id: 18, n: 'sven', l: 'Sven', a: 'str', w: 49.5 },
    { id: 19, n: 'tiny', l: 'Tiny', a: 'str', w: 48.0 },
    { id: 20, n: 'vengefulspirit', l: 'Vengeful Spirit', a: 'uni', w: 52.0 },
    { id: 21, n: 'windrunner', l: 'Windranger', a: 'uni', w: 49.2 },
    { id: 22, n: 'zuus', l: 'Zeus', a: 'int', w: 52.5 },
    { id: 23, n: 'kunkka', l: 'Kunkka', a: 'str', w: 49.8 },
    { id: 25, n: 'lina', l: 'Lina', a: 'int', w: 48.5 },
    { id: 26, n: 'lion', l: 'Lion', a: 'int', w: 49.5 },
    { id: 27, n: 'shadow_shaman', l: 'Shadow Shaman', a: 'int', w: 51.5 },
    { id: 28, n: 'slardar', l: 'Slardar', a: 'str', w: 50.8 },
    { id: 29, n: 'tidehunter', l: 'Tidehunter', a: 'str', w: 50.2 },
    { id: 30, n: 'witch_doctor', l: 'Witch Doctor', a: 'int', w: 51.8 },
    { id: 31, n: 'lich', l: 'Lich', a: 'int', w: 52.0 },
    { id: 32, n: 'riki', l: 'Riki', a: 'agi', w: 51.5 },
    { id: 33, n: 'enigma', l: 'Enigma', a: 'uni', w: 49.0 },
    { id: 34, n: 'tinker', l: 'Tinker', a: 'int', w: 46.5 },
    { id: 35, n: 'sniper', l: 'Sniper', a: 'agi', w: 50.0 },
    { id: 36, n: 'necrolyte', l: 'Necrophos', a: 'int', w: 52.5 },
    { id: 37, n: 'warlock', l: 'Warlock', a: 'int', w: 53.0 },
    { id: 38, n: 'beastmaster', l: 'Beastmaster', a: 'uni', w: 49.5 },
    { id: 39, n: 'queenofpain', l: 'Queen of Pain', a: 'int', w: 48.8 },
    { id: 40, n: 'venomancer', l: 'Venomancer', a: 'uni', w: 52.0 },
    { id: 41, n: 'faceless_void', l: 'Faceless Void', a: 'agi', w: 49.0 },
    { id: 42, n: 'skeleton_king', l: 'Wraith King', a: 'str', w: 53.5 },
    { id: 43, n: 'death_prophet', l: 'Death Prophet', a: 'int', w: 50.8 },
    { id: 44, n: 'phantom_assassin', l: 'Phantom Assassin', a: 'agi', w: 51.0 },
    { id: 45, n: 'pugna', l: 'Pugna', a: 'int', w: 52.0 },
    { id: 46, n: 'templar_assassin', l: 'Templar Assassin', a: 'agi', w: 49.5 },
    { id: 47, n: 'viper', l: 'Viper', a: 'agi', w: 51.5 },
    { id: 48, n: 'luna', l: 'Luna', a: 'agi', w: 51.0 },
    { id: 49, n: 'dragon_knight', l: 'Dragon Knight', a: 'str', w: 51.5 },
    { id: 50, n: 'dazzle', l: 'Dazzle', a: 'uni', w: 51.0 },
    { id: 51, n: 'rattletrap', l: 'Clockwerk', a: 'uni', w: 49.5 },
    { id: 52, n: 'leshrac', l: 'Leshrac', a: 'int', w: 49.0 },
    { id: 53, n: 'furion', l: "Nature's Prophet", a: 'int', w: 48.0 },
    { id: 54, n: 'life_stealer', l: 'Lifestealer', a: 'str', w: 50.5 },
    { id: 55, n: 'dark_seer', l: 'Dark Seer', a: 'uni', w: 49.5 },
    { id: 56, n: 'clinkz', l: 'Clinkz', a: 'agi', w: 50.0 },
    { id: 57, n: 'omniknight', l: 'Omniknight', a: 'str', w: 52.0 },
    { id: 58, n: 'enchantress', l: 'Enchantress', a: 'int', w: 49.0 },
    { id: 59, n: 'huskar', l: 'Huskar', a: 'str', w: 51.0 },
    { id: 60, n: 'night_stalker', l: 'Night Stalker', a: 'str', w: 50.5 },
    { id: 61, n: 'broodmother', l: 'Broodmother', a: 'uni', w: 49.5 },
    { id: 62, n: 'bounty_hunter', l: 'Bounty Hunter', a: 'agi', w: 50.5 },
    { id: 63, n: 'weaver', l: 'Weaver', a: 'agi', w: 50.0 },
    { id: 64, n: 'jakiro', l: 'Jakiro', a: 'int', w: 52.5 },
    { id: 65, n: 'batrider', l: 'Batrider', a: 'uni', w: 48.5 },
    { id: 66, n: 'chen', l: 'Chen', a: 'uni', w: 47.5 },
    { id: 67, n: 'spectre', l: 'Spectre', a: 'agi', w: 52.0 },
    { id: 68, n: 'ancient_apparition', l: 'Ancient Apparition', a: 'int', w: 50.5 },
    { id: 69, n: 'doom_bringer', l: 'Doom', a: 'str', w: 49.0 },
    { id: 70, n: 'ursa', l: 'Ursa', a: 'agi', w: 51.5 },
    { id: 71, n: 'spirit_breaker', l: 'Spirit Breaker', a: 'str', w: 52.0 },
    { id: 72, n: 'gyrocopter', l: 'Gyrocopter', a: 'agi', w: 49.5 },
    { id: 73, n: 'alchemist', l: 'Alchemist', a: 'str', w: 50.0 },
    { id: 74, n: 'invoker', l: 'Invoker', a: 'uni', w: 48.0 },
    { id: 75, n: 'silencer', l: 'Silencer', a: 'int', w: 50.5 },
    { id: 76, n: 'obsidian_destroyer', l: 'Outworld Destroyer', a: 'int', w: 48.0 },
    { id: 77, n: 'lycan', l: 'Lycan', a: 'str', w: 50.5 },
    { id: 78, n: 'brewmaster', l: 'Brewmaster', a: 'uni', w: 48.5 },
    { id: 79, n: 'shadow_demon', l: 'Shadow Demon', a: 'int', w: 48.0 },
    { id: 80, n: 'lone_druid', l: 'Lone Druid', a: 'uni', w: 48.0 },
    { id: 81, n: 'chaos_knight', l: 'Chaos Knight', a: 'str', w: 51.5 },
    { id: 82, n: 'meepo', l: 'Meepo', a: 'agi', w: 49.0 },
    { id: 83, n: 'treant', l: 'Treant Protector', a: 'str', w: 51.5 },
    { id: 84, n: 'ogre_magi', l: 'Ogre Magi', a: 'str', w: 53.0 },
    { id: 85, n: 'undying', l: 'Undying', a: 'str', w: 52.5 },
    { id: 86, n: 'rubick', l: 'Rubick', a: 'int', w: 47.5 },
    { id: 87, n: 'disruptor', l: 'Disruptor', a: 'int', w: 50.0 },
    { id: 88, n: 'nyx_assassin', l: 'Nyx Assassin', a: 'agi', w: 49.0 },
    { id: 89, n: 'naga_siren', l: 'Naga Siren', a: 'agi', w: 50.0 },
    { id: 90, n: 'keeper_of_the_light', l: 'Keeper of the Light', a: 'int', w: 50.0 },
    { id: 91, n: 'wisp', l: 'Io', a: 'uni', w: 44.0 },
    { id: 92, n: 'visage', l: 'Visage', a: 'uni', w: 49.0 },
    { id: 93, n: 'slark', l: 'Slark', a: 'agi', w: 49.5 },
    { id: 94, n: 'medusa', l: 'Medusa', a: 'agi', w: 49.5 },
    { id: 95, n: 'troll_warlord', l: 'Troll Warlord', a: 'agi', w: 50.5 },
    { id: 96, n: 'centaur', l: 'Centaur Warrunner', a: 'str', w: 51.5 },
    { id: 97, n: 'magnataur', l: 'Magnus', a: 'str', w: 48.0 },
    { id: 98, n: 'shredder', l: 'Timbersaw', a: 'str', w: 48.5 },
    { id: 99, n: 'bristleback', l: 'Bristleback', a: 'str', w: 50.5 },
    { id: 100, n: 'tusk', l: 'Tusk', a: 'str', w: 49.5 },
    { id: 101, n: 'skywrath_mage', l: 'Skywrath Mage', a: 'int', w: 49.5 },
    { id: 102, n: 'abaddon', l: 'Abaddon', a: 'uni', w: 53.0 },
    { id: 103, n: 'elder_titan', l: 'Elder Titan', a: 'str', w: 49.5 },
    { id: 104, n: 'legion_commander', l: 'Legion Commander', a: 'str', w: 50.5 },
    { id: 105, n: 'techies', l: 'Techies', a: 'uni', w: 47.0 },
    { id: 106, n: 'ember_spirit', l: 'Ember Spirit', a: 'agi', w: 48.5 },
    { id: 107, n: 'earth_spirit', l: 'Earth Spirit', a: 'str', w: 47.5 },
    { id: 108, n: 'abyssal_underlord', l: 'Underlord', a: 'str', w: 52.5 },
    { id: 109, n: 'terrorblade', l: 'Terrorblade', a: 'agi', w: 49.0 },
    { id: 110, n: 'phoenix', l: 'Phoenix', a: 'str', w: 51.0 },
    { id: 111, n: 'oracle', l: 'Oracle', a: 'int', w: 47.5 },
    { id: 112, n: 'winter_wyvern', l: 'Winter Wyvern', a: 'int', w: 51.5 },
    { id: 113, n: 'arc_warden', l: 'Arc Warden', a: 'agi', w: 48.0 },
    { id: 114, n: 'monkey_king', l: 'Monkey King', a: 'agi', w: 49.0 },
    { id: 119, n: 'dark_willow', l: 'Dark Willow', a: 'int', w: 50.0 },
    { id: 120, n: 'pangolier', l: 'Pangolier', a: 'uni', w: 48.0 },
    { id: 121, n: 'grimstroke', l: 'Grimstroke', a: 'int', w: 49.5 },
    { id: 123, n: 'hoodwink', l: 'Hoodwink', a: 'agi', w: 49.0 },
    { id: 126, n: 'void_spirit', l: 'Void Spirit', a: 'uni', w: 48.5 },
    { id: 128, n: 'snapfire', l: 'Snapfire', a: 'str', w: 51.0 },
    { id: 129, n: 'mars', l: 'Mars', a: 'str', w: 50.0 },
    { id: 131, n: 'ringmaster', l: 'Ringmaster', a: 'int', w: 49.0 },
    { id: 135, n: 'dawnbreaker', l: 'Dawnbreaker', a: 'str', w: 51.5 },
    { id: 136, n: 'marci', l: 'Marci', a: 'uni', w: 50.5 },
    { id: 137, n: 'primal_beast', l: 'Primal Beast', a: 'str', w: 50.5 },
    { id: 138, n: 'muerta', l: 'Muerta', a: 'int', w: 49.5 },
    { id: 145, n: 'kez', l: 'Kez', a: 'agi', w: 48.5 },
];

// Build lookup maps
const HERO_BY_ID = {};
const HERO_BY_NAME = {};
HEROES.forEach(h => {
    HERO_BY_ID[h.id] = h;
    HERO_BY_NAME[h.n] = h;
});

function getHeroImg(hero) {
    return `${HERO_CDN}${hero.n}.png`;
}

function getHeroImgById(id) {
    const h = HERO_BY_ID[id];
    return h ? getHeroImg(h) : '';
}
